---
- name: Add Repository MongoDB
  yum_repository: 
    name: mongodb-org-4.0
    description: External Repo MongoDB
    file:  mongodb_repos
    baseurl: "{{ mongodb_baseurl }}"
    enabled: yes
    gpgcheck: yes
    gpgkey: "{{ mongodb_gpgkey_url }}"

- name: Installation de mongodb-org
  yum:
    name: "{{ item }}"
    state: present 
    update_cache: yes
  loop:
    - mongodb-org 

- name: Start de MongoDB
  systemd:
    name: mongod
    state: started
    daemon_reload: yes
    enabled: yes

- name: Configuration de MongoDB
  template:
    src: mongo_conf.j2
    dest: /etc/mongod.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart MongoDB

- firewalld:
    port: 27017/tcp
    permanent: yes
    state: enabled
