---
- name: Install unzip si non installe
  yum: 
    name: "{{ item }}"
    state: present
  loop:
    - unzip

- name: Unarchive nodecellar
  unarchive:
    src: "{{ NODECELLAR_URL }}"
    dest: "/opt"
    remote_src: yes 

- name: Install packages based on package.json.
  npm:
    path: "/opt/nodecellar-master/"

- name: Installation du service nodecellar
  template:
    src: nodecellar_unit.j2
    dest: /usr/lib/systemd/system/nodecellar.service  

- name: Declaration du serveur MongoDB
  lineinfile:
    path: /opt/nodecellar-master/routes/wines.js
    regexp: '^(.*)localhost(.*)$'
    line: "var server = new Server('client-node04.halimi.lan', 27017, {auto_reconnect: true});"

- name: Start nodecellar.service
  systemd:
    name: nodecellar.service
    state: restarted
    enabled: yes
