---
- name: Install unzip si non installe
  yum: 
    name: "{{ item }}"
    state: present
  loop:
    - unzip

- name: Unarchive nodecellar
  unarchive:
    src: "{{ nodecellar_url }}"
    dest: "/opt"
    remote_src: yes 
  notify: Start nodecellar.service

- name: Change Owner /opt/nodecellar-master/
  file:
    path: /opt/nodecellar-master
    owner: hassan
    group: hassan
    recurse: yes

- name: Install packages based on package.json.
  npm:
    path: "/opt/nodecellar-master/"

- name: Installation du service nodecellar
  template:
    src: nodecellar_unit.j2
    dest: /usr/lib/systemd/system/nodecellar.service  
  notify: Start nodecellar.service

- name: Start nodecellar.service
  systemd:
    name: nodecellar.service
    state: started
    enabled: yes
    daemon_reload: yes
